### ISSUE TITLE
Team Codekarletehai - Relay-bridge

### ISSUE THREAD

**Issue by harsh-98** [hackferenceindia/submissions#16]
**Before you start, please follow this format for your issue title**:  
Codekarletehai - Relay-bridge

## ℹ️ Project information
_Relay-bridge is an blockchain technology which allows uses to trade assets and tokens between different blockchain. This implementation is focused on using the POA-network's relay-bridge technology for exchanging ERC20 with ERC667._

- **Project Name**: Relay-bridge
- **Short Project Description**: _It is an implementation of bridge-relay between ERC20 and ERC667_
- **Team Name**: Codekarletehai
- **Team Members**: _harsh jain@harsh-98_
- **Demo Link**: _(if any, this might contain a website/ mobile application link/ short video, etc.)_
- **Repository Link**: _https://github.com/harsh-98/relay-bridge_
- **Labels**: _blockchain_

## 🔥 Your Pitch
In the future, we see a world filled with diverse blockchains all serving specific and unique purposes. Currently, these blockchain networks exist in isolation with no communication or interoperability between them. 
This is an existential problem that needs to be addressed in order for a truly trustless ecosystem to develop and thrive. Currently, if one want to exchange zcash for ethereum then he has to relay on a centralized exchange authority, which aften maintains off chain orders (orderbook of the transactions). This differ from decentralised aspect of blockchain technology and due to this when exchanges are hacked they can loss millions. 

## 🔦 Any other specific thing you want to highlight?
_(Optional)_

## ✅ Checklist

**Before you post the issue**:
- [x] You have followed the issue title format.
- [x] You have mentioned the correct labels.
- [x] You have provided all the information correctly.

**Comment by yashovardhan** [comment]
@harsh-98 mention the track, kindly go through the README.md file for more information about the track label

**Comment by harsh-98** [comment]
I didn't have the permission to add label. Labels are:
Blockchain Track 3
Blockchain
So, can you add the missing label and reopen the issue.

**Comment by yashovardhan** [comment]
you didn't mention it at the time of the Hackathon..

sorry but this will be termed as an invalid submission now.

**Comment by harsh-98** [comment]
but i got it checked by the xinfin team.

**Comment by yashovardhan** [comment]
you can submit the issue in their repository for the same

**Comment by harsh-98** [comment]
i submitted that on the same day.

**Comment by yashovardhan** [comment]
sure, thanks they will handle it from their side then

**Comment by harsh-98** [comment]
But i want to know where this submission would be valid or not as in reimbursement form it was given only valid submssions will be considered.

**Comment by yashovardhan** [comment]
As per Hackference rules, this submission will not be valid.

**Comment by harsh-98** [comment]
What about the travel reimbursement? i was there at the event.

**Comment by yashovardhan** [comment]
Sorry, but as per rules there should be a valid submission for travel reimbursement.
