### ISSUE TITLE
SAHAJYA APP

### ISSUE THREAD

**Issue by Sharo31** [hackferenceindia/submissions#31]
**Before you start, please follow this format for your issue title**:  
SHAWSHANK-SAHAJYA APP

## ℹ️ Project information
_Please complete all applicable._

- **SAHAJYA APP**:
- **Short Project Description**: One-stop solution to all disaster relief situations.
- **Team Name**:SHAWSHANK
- **Team Members**: Subhojit Mohanty @Sharo31,Vaibhav Seth @vaibhav1seth, Jigyans Mohapatra @Jkminvader
- **Demo Link**: https://drive.google.com/open?id=1aTh22DraR5QzNPDWLcFO1FKdKm8gPRiP
- **Repository Link**:https://github.com/Sharo31/SahajyaWeb.git
https://github.com/Sharo31/SahajyaApp.git
https://github.com/Sharo31/LocationPrioritiser.git
- **Labels**: OPEN INNOVATION

## 🔥 Your Pitch
It is the one stop solution to all disaster relief situations. The better the communication channel, the lesser death toll. Our USP is to empower people to help themselves out of crunch situations without any external help.
We have taken into consideration multiple scenarios during a flood relief situation and gave possible solutions to it. It has been listed below. ONE PROJECT-MULTIPLE PLATFORM

*************FEATURES OF OUR PROJECT********************

1.Medical Assistance: In case of minor injuries, victims can chat with the doctor.

2.Medical Emergency: In case of severe injuries, people can pinpoint their location and a little bit of description.

3.Relief Drops/Camps: Whenever the rescue team is setting up a camp or dropping relief items, they can pinpoint the location on the map which enables victims to reach out to that place with any external help.

4.Missing People: We have created a portal where people who find such lost kids can update their profile and describe the locations. Concerned parties can reach out to the place, hence reducing the mental trauma.

5.Volunteer Signup: No matter how much help we have, we need more people to come up for the cause.  People can register as volunteers and can specify the camp where they will be volunteering. 

***************TECHNOLOGY STACK*******************

Our project has 3  Client Sides and 1 Server Side.
1. Sahajya App: The primary app which can be used by victims.
2. WEB Application: This is handled by the NDRF/Rescue Team where they monitor the request made by the victims and act accordingly.
3.AskDoc: This is for the doctors who will be chatting with the victims to provide help.

#App is built in ANDROID STUDIO.
#Webpage is built on REACT JS, we have incorporated MACHINE LEARNING to prioritize the locations where the emergency is maximum.
#FIREBASE Firestore is used as our primary database, which is common for all the 3 Client Sides.
#IOT DEVICE which could transmit distress signals in the form of Radio waves, hence providing solutions when Mobile Network is absent and the app fails to perform.

***************NEW AGE IMPLEMENTATIONS*****************

1.SHAKE GESTURE: Making use of the ACCELEROMETER present in phones so that illiterate people can also send their distress locations to the rescue team database with just a shake of the phone. This ensures the covering of a larger mass.

2. I TALK : As google assistant is actively present in JIO phones(cheap), We have created a GOOGLE ASSISTANT SKILL will enable people to converse with the assistant and provide details which goes to the rescue team database. Ensuring greater accessibility to the people.

## 🔦 Any other specific thing you want to highlight?
_(Optional)_

## ✅ Checklist

**Before you post the issue**:
- [ ] You have followed the issue title format.
- [ ] You have mentioned the correct labels.
- [ ] You have provided all the information correctly.

**Comment by yashovardhanagrawal** [comment]
@Sharo31 please mention your track label
