### ISSUE TITLE
TeamCtrl_alt_del- Auto2Manual

### ISSUE THREAD

**Issue by archithdwij** [hackferenceindia/submissions#32]
ℹ️ Project information

- Project Name: Auto2Manual
- Short Project Description: You work, to make the app work for you
- Team Name: ctrl_alt_del
- Team Members: Archith Dwij .H.P - codehack31, Akash Sharma - Akash2599, Ajith Kumar .K - ajithkumar9
- **Repository Link**: https://github.com/codehack31/Auto2MANUAL
- Labels: Eliminating the Laziness - Being Human 

 🔥 Your Pitch
   In this technology-driven generation, human effort is getting lesser day by day and is getting replaced with machines. People, on the other hand, are becoming lazy as technology is becoming their best friend. Every morning starts with WhatsApp and Instagram posts instead of coffee.
-	This situation is worse than bed coffee. So bringing some manual work to this automation, we replace the regular app locks with a paradigm which we call *AUTO2MANUAL*. This requests the user to walk (or) run to a certain distance so that the app vault opens. This is actually making a person exercise a little bit and making it mandatory will not make them not to open the app as the information behind the vault is magical. As this application is place-dependant, there will be some questions to which the user will answer to explain their surroundings. If they are inside their workspace, then they can switch to some mental exercises or puzzles that relaxes their mind and keep them refreshed. When they think surfing the Insta-posts is relaxing, these mind games are the actual stress busters. In this way, we are adding some knowledge (both physical and mental) with fun.

**Comment by yashovardhan** [comment]
@codehack31 please mention the right labels

go through the README.md file for more information
